const shortcuts = [
  // ========== 一般的なショートカット ==========
  { id: 1, category: "一般", action: "コピー", mac: "⌘ + C", windows: "Ctrl + C", description: "選択したテキストやファイルをクリップボードにコピー", tags: ["コピー", "copy", "クリップボード"] },
  { id: 2, category: "一般", action: "ペースト（貼り付け）", mac: "⌘ + V", windows: "Ctrl + V", description: "クリップボードの内容を貼り付け", tags: ["ペースト", "貼り付け", "paste", "クリップボード"] },
  { id: 3, category: "一般", action: "切り取り", mac: "⌘ + X", windows: "Ctrl + X", description: "選択したテキストやファイルを切り取り", tags: ["切り取り", "cut", "カット"] },
  { id: 4, category: "一般", action: "元に戻す", mac: "⌘ + Z", windows: "Ctrl + Z", description: "直前の操作を取り消し", tags: ["元に戻す", "undo", "取り消し", "アンドゥ"] },
  { id: 5, category: "一般", action: "やり直し", mac: "⌘ + Shift + Z", windows: "Ctrl + Y", description: "元に戻した操作をやり直し", tags: ["やり直し", "redo", "リドゥ"] },
  { id: 6, category: "一般", action: "すべて選択", mac: "⌘ + A", windows: "Ctrl + A", description: "すべての項目を選択", tags: ["すべて選択", "全選択", "select all"] },
  { id: 7, category: "一般", action: "検索", mac: "⌘ + F", windows: "Ctrl + F", description: "ページ内検索を開く", tags: ["検索", "find", "search", "探す"] },
  { id: 8, category: "一般", action: "保存", mac: "⌘ + S", windows: "Ctrl + S", description: "現在のドキュメントを保存", tags: ["保存", "save", "セーブ"] },
  { id: 9, category: "一般", action: "印刷", mac: "⌘ + P", windows: "Ctrl + P", description: "印刷ダイアログを開く", tags: ["印刷", "print", "プリント"] },
  { id: 10, category: "一般", action: "新規作成", mac: "⌘ + N", windows: "Ctrl + N", description: "新しいドキュメントやウィンドウを作成", tags: ["新規", "new", "作成"] },
  { id: 11, category: "一般", action: "開く", mac: "⌘ + O", windows: "Ctrl + O", description: "ファイルを開くダイアログを表示", tags: ["開く", "open", "ファイル"] },
  { id: 12, category: "一般", action: "閉じる", mac: "⌘ + W", windows: "Ctrl + W", description: "現在のウィンドウやタブを閉じる", tags: ["閉じる", "close", "クローズ"] },
  { id: 13, category: "一般", action: "終了", mac: "⌘ + Q", windows: "Alt + F4", description: "アプリケーションを終了", tags: ["終了", "quit", "exit", "閉じる"] },

  // ========== テキスト編集 ==========
  { id: 14, category: "テキスト編集", action: "太字", mac: "⌘ + B", windows: "Ctrl + B", description: "選択したテキストを太字に", tags: ["太字", "bold", "ボールド"] },
  { id: 15, category: "テキスト編集", action: "斜体", mac: "⌘ + I", windows: "Ctrl + I", description: "選択したテキストを斜体に", tags: ["斜体", "italic", "イタリック"] },
  { id: 16, category: "テキスト編集", action: "下線", mac: "⌘ + U", windows: "Ctrl + U", description: "選択したテキストに下線を追加", tags: ["下線", "underline", "アンダーライン"] },
  { id: 17, category: "テキスト編集", action: "行の先頭へ移動", mac: "⌘ + ←", windows: "Home", description: "カーソルを行の先頭に移動", tags: ["行頭", "先頭", "home", "移動"] },
  { id: 18, category: "テキスト編集", action: "行の末尾へ移動", mac: "⌘ + →", windows: "End", description: "カーソルを行の末尾に移動", tags: ["行末", "末尾", "end", "移動"] },
  { id: 19, category: "テキスト編集", action: "単語単位で移動（左）", mac: "Option + ←", windows: "Ctrl + ←", description: "カーソルを単語単位で左に移動", tags: ["単語", "word", "移動", "左"] },
  { id: 20, category: "テキスト編集", action: "単語単位で移動（右）", mac: "Option + →", windows: "Ctrl + →", description: "カーソルを単語単位で右に移動", tags: ["単語", "word", "移動", "右"] },
  { id: 21, category: "テキスト編集", action: "ドキュメントの先頭へ", mac: "⌘ + ↑", windows: "Ctrl + Home", description: "カーソルをドキュメントの先頭に移動", tags: ["先頭", "top", "文書", "移動"] },
  { id: 22, category: "テキスト編集", action: "ドキュメントの末尾へ", mac: "⌘ + ↓", windows: "Ctrl + End", description: "カーソルをドキュメントの末尾に移動", tags: ["末尾", "bottom", "文書", "移動"] },

  // ========== ブラウザ ==========
  { id: 23, category: "ブラウザ", action: "新しいタブ", mac: "⌘ + T", windows: "Ctrl + T", description: "新しいタブを開く", tags: ["タブ", "tab", "新規", "ブラウザ"] },
  { id: 24, category: "ブラウザ", action: "タブを閉じる", mac: "⌘ + W", windows: "Ctrl + W", description: "現在のタブを閉じる", tags: ["タブ", "tab", "閉じる", "ブラウザ"] },
  { id: 25, category: "ブラウザ", action: "閉じたタブを復元", mac: "⌘ + Shift + T", windows: "Ctrl + Shift + T", description: "最後に閉じたタブを再度開く", tags: ["タブ", "復元", "reopen", "ブラウザ"] },
  { id: 26, category: "ブラウザ", action: "次のタブ", mac: "⌘ + Option + →", windows: "Ctrl + Tab", description: "次のタブに移動", tags: ["タブ", "tab", "次", "移動", "ブラウザ"] },
  { id: 27, category: "ブラウザ", action: "前のタブ", mac: "⌘ + Option + ←", windows: "Ctrl + Shift + Tab", description: "前のタブに移動", tags: ["タブ", "tab", "前", "移動", "ブラウザ"] },
  { id: 28, category: "ブラウザ", action: "ページを再読み込み", mac: "⌘ + R", windows: "Ctrl + R / F5", description: "現在のページを再読み込み", tags: ["リロード", "reload", "更新", "refresh", "ブラウザ"] },
  { id: 29, category: "ブラウザ", action: "強制再読み込み", mac: "⌘ + Shift + R", windows: "Ctrl + Shift + R", description: "キャッシュを無視してページを再読み込み", tags: ["リロード", "reload", "キャッシュ", "ブラウザ"] },
  { id: 30, category: "ブラウザ", action: "アドレスバーにフォーカス", mac: "⌘ + L", windows: "Ctrl + L / F6", description: "アドレスバーを選択", tags: ["アドレス", "URL", "ブラウザ", "フォーカス"] },
  { id: 31, category: "ブラウザ", action: "ブックマーク追加", mac: "⌘ + D", windows: "Ctrl + D", description: "現在のページをブックマークに追加", tags: ["ブックマーク", "bookmark", "お気に入り", "ブラウザ"] },
  { id: 32, category: "ブラウザ", action: "開発者ツール", mac: "⌘ + Option + I", windows: "F12 / Ctrl + Shift + I", description: "開発者ツールを開く", tags: ["開発者ツール", "devtools", "inspect", "デバッグ", "ブラウザ"] },
  { id: 33, category: "ブラウザ", action: "戻る", mac: "⌘ + [", windows: "Alt + ←", description: "前のページに戻る", tags: ["戻る", "back", "ブラウザ", "ナビゲーション"] },
  { id: 34, category: "ブラウザ", action: "進む", mac: "⌘ + ]", windows: "Alt + →", description: "次のページに進む", tags: ["進む", "forward", "ブラウザ", "ナビゲーション"] },
  { id: 35, category: "ブラウザ", action: "ズームイン", mac: "⌘ + +", windows: "Ctrl + +", description: "ページを拡大", tags: ["ズーム", "拡大", "zoom", "ブラウザ"] },
  { id: 36, category: "ブラウザ", action: "ズームアウト", mac: "⌘ + -", windows: "Ctrl + -", description: "ページを縮小", tags: ["ズーム", "縮小", "zoom", "ブラウザ"] },
  { id: 37, category: "ブラウザ", action: "シークレットウィンドウ", mac: "⌘ + Shift + N", windows: "Ctrl + Shift + N", description: "新しいシークレット/プライベートウィンドウを開く", tags: ["シークレット", "プライベート", "incognito", "ブラウザ"] },

  // ========== システム（Mac） ==========
  { id: 38, category: "システム（Mac）", action: "Spotlight検索", mac: "⌘ + Space", windows: "-", description: "Spotlight検索を開く", tags: ["spotlight", "検索", "search", "mac"] },
  { id: 39, category: "システム（Mac）", action: "スクリーンショット（全画面）", mac: "⌘ + Shift + 3", windows: "Print Screen", description: "画面全体のスクリーンショットを撮影", tags: ["スクリーンショット", "screenshot", "画面キャプチャ"] },
  { id: 40, category: "システム（Mac）", action: "スクリーンショット（範囲選択）", mac: "⌘ + Shift + 4", windows: "Win + Shift + S", description: "選択範囲のスクリーンショットを撮影", tags: ["スクリーンショット", "screenshot", "画面キャプチャ", "範囲"] },
  { id: 41, category: "システム（Mac）", action: "スクリーンショット（ウィンドウ）", mac: "⌘ + Shift + 4 + Space", windows: "Alt + Print Screen", description: "ウィンドウのスクリーンショットを撮影", tags: ["スクリーンショット", "screenshot", "ウィンドウ"] },
  { id: 42, category: "システム（Mac）", action: "Mission Control", mac: "Control + ↑ / F3", windows: "-", description: "Mission Controlを開く", tags: ["mission control", "ウィンドウ", "mac"] },
  { id: 43, category: "システム（Mac）", action: "デスクトップを表示", mac: "F11 / ⌘ + F3", windows: "Win + D", description: "デスクトップを表示", tags: ["デスクトップ", "desktop", "表示"] },
  { id: 44, category: "システム（Mac）", action: "アプリの切り替え", mac: "⌘ + Tab", windows: "Alt + Tab", description: "開いているアプリを切り替え", tags: ["切り替え", "switch", "アプリ", "tab"] },
  { id: 45, category: "システム（Mac）", action: "同一アプリのウィンドウ切り替え", mac: "⌘ + `", windows: "-", description: "同じアプリの別ウィンドウに切り替え", tags: ["ウィンドウ", "切り替え", "mac"] },
  { id: 46, category: "システム（Mac）", action: "強制終了ダイアログ", mac: "⌘ + Option + Esc", windows: "Ctrl + Shift + Esc", description: "アプリケーションの強制終了ダイアログを開く", tags: ["強制終了", "force quit", "タスクマネージャー"] },
  { id: 47, category: "システム（Mac）", action: "画面ロック", mac: "⌘ + Control + Q", windows: "Win + L", description: "画面をロック", tags: ["ロック", "lock", "画面"] },
  { id: 48, category: "システム（Mac）", action: "クイックルック", mac: "Space", windows: "-", description: "Finderで選択したファイルをプレビュー", tags: ["クイックルック", "quick look", "プレビュー", "finder"] },
  { id: 49, category: "システム（Mac）", action: "絵文字ピッカー", mac: "⌘ + Control + Space", windows: "Win + .", description: "絵文字入力パネルを開く", tags: ["絵文字", "emoji", "顔文字"] },

  // ========== システム（Windows） ==========
  { id: 50, category: "システム（Windows）", action: "スタートメニュー", mac: "-", windows: "Win", description: "スタートメニューを開く", tags: ["スタート", "start", "メニュー", "windows"] },
  { id: 51, category: "システム（Windows）", action: "設定を開く", mac: "-", windows: "Win + I", description: "Windowsの設定を開く", tags: ["設定", "settings", "windows"] },
  { id: 52, category: "システム（Windows）", action: "エクスプローラーを開く", mac: "-", windows: "Win + E", description: "ファイルエクスプローラーを開く", tags: ["エクスプローラー", "explorer", "ファイル", "windows"] },
  { id: 53, category: "システム（Windows）", action: "仮想デスクトップ切り替え", mac: "Control + ← / →", windows: "Win + Ctrl + ← / →", description: "仮想デスクトップを切り替え", tags: ["仮想デスクトップ", "virtual desktop", "切り替え"] },
  { id: 54, category: "システム（Windows）", action: "新しい仮想デスクトップ", mac: "-", windows: "Win + Ctrl + D", description: "新しい仮想デスクトップを作成", tags: ["仮想デスクトップ", "virtual desktop", "新規"] },
  { id: 55, category: "システム（Windows）", action: "タスクビュー", mac: "-", windows: "Win + Tab", description: "タスクビューを開く", tags: ["タスクビュー", "task view", "ウィンドウ", "windows"] },
  { id: 56, category: "システム（Windows）", action: "ウィンドウを左半分にスナップ", mac: "-", windows: "Win + ←", description: "ウィンドウを画面の左半分にスナップ", tags: ["スナップ", "snap", "ウィンドウ", "左"] },
  { id: 57, category: "システム（Windows）", action: "ウィンドウを右半分にスナップ", mac: "-", windows: "Win + →", description: "ウィンドウを画面の右半分にスナップ", tags: ["スナップ", "snap", "ウィンドウ", "右"] },
  { id: 58, category: "システム（Windows）", action: "ウィンドウを最大化", mac: "-", windows: "Win + ↑", description: "ウィンドウを最大化", tags: ["最大化", "maximize", "ウィンドウ"] },
  { id: 59, category: "システム（Windows）", action: "ウィンドウを最小化", mac: "⌘ + M", windows: "Win + ↓", description: "ウィンドウを最小化", tags: ["最小化", "minimize", "ウィンドウ"] },
  { id: 60, category: "システム（Windows）", action: "クリップボード履歴", mac: "-", windows: "Win + V", description: "クリップボード履歴を表示", tags: ["クリップボード", "clipboard", "履歴", "windows"] },

  // ========== VS Code / エディタ ==========
  { id: 61, category: "VS Code", action: "コマンドパレット", mac: "⌘ + Shift + P", windows: "Ctrl + Shift + P", description: "コマンドパレットを開く", tags: ["コマンド", "command", "palette", "vscode"] },
  { id: 62, category: "VS Code", action: "クイックオープン", mac: "⌘ + P", windows: "Ctrl + P", description: "ファイルをすばやく開く", tags: ["ファイル", "開く", "quick open", "vscode"] },
  { id: 63, category: "VS Code", action: "行を複製", mac: "⌘ + Shift + D", windows: "Ctrl + Shift + D", description: "現在の行を複製", tags: ["複製", "duplicate", "行", "vscode"] },
  { id: 64, category: "VS Code", action: "行を移動（上）", mac: "Option + ↑", windows: "Alt + ↑", description: "現在の行を上に移動", tags: ["移動", "行", "上", "vscode"] },
  { id: 65, category: "VS Code", action: "行を移動（下）", mac: "Option + ↓", windows: "Alt + ↓", description: "現在の行を下に移動", tags: ["移動", "行", "下", "vscode"] },
  { id: 66, category: "VS Code", action: "行を削除", mac: "⌘ + Shift + K", windows: "Ctrl + Shift + K", description: "現在の行を削除", tags: ["削除", "行", "delete", "vscode"] },
  { id: 67, category: "VS Code", action: "マルチカーソル", mac: "⌘ + Option + ↑/↓", windows: "Ctrl + Alt + ↑/↓", description: "複数行にカーソルを追加", tags: ["マルチカーソル", "multi cursor", "vscode"] },
  { id: 68, category: "VS Code", action: "同じ単語を選択", mac: "⌘ + D", windows: "Ctrl + D", description: "同じ単語の次の出現を選択に追加", tags: ["選択", "単語", "マルチ", "vscode"] },
  { id: 69, category: "VS Code", action: "行コメント切り替え", mac: "⌘ + /", windows: "Ctrl + /", description: "行コメントの切り替え", tags: ["コメント", "comment", "vscode"] },
  { id: 70, category: "VS Code", action: "ブロックコメント切り替え", mac: "⌘ + Shift + /", windows: "Ctrl + Shift + /", description: "ブロックコメントの切り替え", tags: ["コメント", "ブロック", "comment", "vscode"] },
  { id: 71, category: "VS Code", action: "定義に移動", mac: "F12", windows: "F12", description: "シンボルの定義に移動", tags: ["定義", "definition", "ジャンプ", "vscode"] },
  { id: 72, category: "VS Code", action: "参照を検索", mac: "Shift + F12", windows: "Shift + F12", description: "シンボルの参照を検索", tags: ["参照", "reference", "検索", "vscode"] },
  { id: 73, category: "VS Code", action: "リネーム", mac: "F2", windows: "F2", description: "シンボルの名前を変更", tags: ["リネーム", "rename", "名前変更", "vscode"] },
  { id: 74, category: "VS Code", action: "サイドバー表示切り替え", mac: "⌘ + B", windows: "Ctrl + B", description: "サイドバーの表示/非表示を切り替え", tags: ["サイドバー", "sidebar", "vscode"] },
  { id: 75, category: "VS Code", action: "ターミナル表示切り替え", mac: "⌘ + `", windows: "Ctrl + `", description: "統合ターミナルの表示/非表示を切り替え", tags: ["ターミナル", "terminal", "vscode"] },
  { id: 76, category: "VS Code", action: "エディタの分割", mac: "⌘ + \\", windows: "Ctrl + \\", description: "エディタを分割", tags: ["分割", "split", "エディタ", "vscode"] },

  // ========== Finder / ファイル管理 ==========
  { id: 77, category: "Finder / エクスプローラー", action: "新しいフォルダ", mac: "⌘ + Shift + N", windows: "Ctrl + Shift + N", description: "新しいフォルダを作成", tags: ["フォルダ", "folder", "新規", "作成"] },
  { id: 78, category: "Finder / エクスプローラー", action: "ファイル名を変更", mac: "Enter", windows: "F2", description: "選択したファイルの名前を変更", tags: ["名前変更", "rename", "ファイル"] },
  { id: 79, category: "Finder / エクスプローラー", action: "ゴミ箱に移動", mac: "⌘ + Delete", windows: "Delete", description: "選択したファイルをゴミ箱に移動", tags: ["削除", "delete", "ゴミ箱"] },
  { id: 80, category: "Finder / エクスプローラー", action: "完全に削除", mac: "⌘ + Option + Delete", windows: "Shift + Delete", description: "ゴミ箱を経由せずに削除", tags: ["削除", "delete", "完全削除"] },
  { id: 81, category: "Finder / エクスプローラー", action: "情報を見る", mac: "⌘ + I", windows: "Alt + Enter", description: "ファイルの情報/プロパティを表示", tags: ["情報", "info", "プロパティ"] },
  { id: 82, category: "Finder / エクスプローラー", action: "隠しファイルを表示", mac: "⌘ + Shift + .", windows: "-", description: "隠しファイルの表示を切り替え", tags: ["隠しファイル", "hidden", "表示"] },
  { id: 83, category: "Finder / エクスプローラー", action: "親フォルダに移動", mac: "⌘ + ↑", windows: "Alt + ↑", description: "親フォルダに移動", tags: ["移動", "親フォルダ", "上"] },

  // ========== Slack ==========
  { id: 84, category: "Slack", action: "クイックスイッチャー", mac: "⌘ + K", windows: "Ctrl + K", description: "チャンネルやDMをすばやく切り替え", tags: ["slack", "切り替え", "チャンネル", "検索"] },
  { id: 85, category: "Slack", action: "メッセージを編集", mac: "↑", windows: "↑", description: "最後に送ったメッセージを編集", tags: ["slack", "編集", "メッセージ"] },
  { id: 86, category: "Slack", action: "絵文字リアクション", mac: "⌘ + Shift + \\", windows: "Ctrl + Shift + \\", description: "メッセージに絵文字リアクションを追加", tags: ["slack", "リアクション", "絵文字"] },
  { id: 87, category: "Slack", action: "未読に移動", mac: "⌘ + Shift + A", windows: "Ctrl + Shift + A", description: "未読メッセージに移動", tags: ["slack", "未読", "メッセージ"] },

  // ========== Excel / スプレッドシート ==========
  { id: 88, category: "Excel / スプレッドシート", action: "セルの編集", mac: "F2", windows: "F2", description: "選択したセルを編集モードに", tags: ["excel", "編集", "セル"] },
  { id: 89, category: "Excel / スプレッドシート", action: "行を挿入", mac: "⌘ + Shift + +", windows: "Ctrl + Shift + +", description: "新しい行を挿入", tags: ["excel", "行", "挿入"] },
  { id: 90, category: "Excel / スプレッドシート", action: "行を削除", mac: "⌘ + -", windows: "Ctrl + -", description: "選択した行を削除", tags: ["excel", "行", "削除"] },
  { id: 91, category: "Excel / スプレッドシート", action: "オートSUM", mac: "⌘ + Shift + T", windows: "Alt + =", description: "SUM関数を自動挿入", tags: ["excel", "sum", "合計", "関数"] },
  { id: 92, category: "Excel / スプレッドシート", action: "値のみ貼り付け", mac: "⌘ + Shift + V", windows: "Ctrl + Shift + V", description: "書式なしで値のみ貼り付け", tags: ["excel", "貼り付け", "値", "ペースト"] },
  { id: 93, category: "Excel / スプレッドシート", action: "絶対参照の切り替え", mac: "⌘ + T / F4", windows: "F4", description: "セル参照の絶対/相対を切り替え", tags: ["excel", "参照", "絶対", "相対", "ドル"] },
  { id: 94, category: "Excel / スプレッドシート", action: "今日の日付を挿入", mac: "Control + ;", windows: "Ctrl + ;", description: "現在の日付を挿入", tags: ["excel", "日付", "today"] },

  // ========== ターミナル ==========
  { id: 95, category: "ターミナル", action: "コマンドを中断", mac: "Control + C", windows: "Ctrl + C", description: "実行中のコマンドを中断", tags: ["ターミナル", "terminal", "中断", "キャンセル"] },
  { id: 96, category: "ターミナル", action: "画面をクリア", mac: "⌘ + K / Control + L", windows: "cls / Ctrl + L", description: "ターミナル画面をクリア", tags: ["ターミナル", "terminal", "クリア", "clear"] },
  { id: 97, category: "ターミナル", action: "前のコマンド", mac: "↑", windows: "↑", description: "コマンド履歴を遡る", tags: ["ターミナル", "terminal", "履歴", "history"] },
  { id: 98, category: "ターミナル", action: "オートコンプリート", mac: "Tab", windows: "Tab", description: "コマンドやパスを自動補完", tags: ["ターミナル", "terminal", "補完", "autocomplete"] },
  { id: 99, category: "ターミナル", action: "コマンド履歴を検索", mac: "Control + R", windows: "Ctrl + R", description: "コマンド履歴をインタラクティブに検索", tags: ["ターミナル", "terminal", "検索", "履歴"] },

  // ========== Zoom ==========
  { id: 100, category: "Zoom", action: "ミュート切り替え", mac: "⌘ + Shift + A", windows: "Alt + A", description: "マイクのミュート/ミュート解除", tags: ["zoom", "ミュート", "mute", "マイク"] },
  { id: 101, category: "Zoom", action: "ビデオ切り替え", mac: "⌘ + Shift + V", windows: "Alt + V", description: "ビデオのオン/オフを切り替え", tags: ["zoom", "ビデオ", "video", "カメラ"] },
  { id: 102, category: "Zoom", action: "画面共有", mac: "⌘ + Shift + S", windows: "Alt + S", description: "画面共有を開始/停止", tags: ["zoom", "画面共有", "share", "screen"] },
  { id: 103, category: "Zoom", action: "チャットを開く", mac: "⌘ + Shift + H", windows: "Alt + H", description: "ミーティングチャットを開く", tags: ["zoom", "チャット", "chat"] },
  { id: 104, category: "Zoom", action: "手を挙げる", mac: "Option + Y", windows: "Alt + Y", description: "手を挙げる/下げる", tags: ["zoom", "手を挙げる", "raise hand"] },
];
